### PR TITLE
fix(swagger): add compatibility with nest swagger v4

### LINKED ISSUE #79: swagger description is too long
some ways to make it short
1. support custom swagger description
2. make it short like using url instead of large text 
3. just an options to disable them all

### PR DESCRIPTION
**Pull request by zMotivat0r**
- add compatibility with nest swagger v4

fix #79, #314

### CODE REVIEW

**Comment by leosuncin** [comment]
Still failing

**With the current versions**
@nestjs/common: 6.10.10
@nestjs/core: 6.10.10
@nestjs/swagger: 4.0.9
@nestjsx/crud: 4.3.0-alpha.0
@nestjsx/crud-typeorm: 4.3.0-alpha.0

**Stacktrace**
```
TypeError: ApiModelProperty is not a function
    at /home/user/project/node_modules/@nestjsx/crud/src/crud/validation.helper.ts:19:7
    at DecorateProperty (/home/user/project/node_modules/reflect-metadata/Reflect.js:553:33)
    at Object.decorate (/home/user/project/node_modules/reflect-metadata/Reflect.js:123:24)
    at __decorate (/home/user/project/node_modules/@nestjsx/crud/lib/crud/validation.helper.js:4:92)
    at Function.createBulkDto (/home/user/project/node_modules/@nestjsx/crud/src/crud/validation.helper.ts:54:9)
    at CrudRoutesFactory.setRouteArgsTypes (/home/user/project/node_modules/@nestjsx/crud/src/crud/crud-routes.factory.ts:371:34)
    at CrudRoutesFactory.setBaseRouteMeta (/home/user/project/node_modules/@nestjsx/crud/src/crud/crud-routes.factory.ts:338:10)
    at /home/user/project/node_modules/@nestjsx/crud/src/crud/crud-routes.factory.ts:230:14
    at Array.forEach (<anonymous>)
    at CrudRoutesFactory.createRoutes (/home/user/project/node_modules/@nestjsx/crud/src/crud/crud-routes.factory.ts:224:18)
```

**Comment by jakemonton** [comment]
Issue still occur

"@nestjs/common": "^6.7.2",
"@nestjs/core": "^6.7.2",
"@nestjs/swagger": "^4.0.0-next.19",
"@nestjsx/crud": "^4.2.0",
"@nestjsx/crud-typeorm": "^4.2.0",
"swagger-ui-express": "^4.1.2"

**Comment by zMotivat0r** [comment]
published `4.3.0-beta.0`

**Comment by evrend** [comment]
> published `4.3.0-beta.0`

This version working with  `"@nestjs/swagger": "^4.0.9"`.  
Thanks.

**Comment by hakimio** [comment]
@zMotivat0r 
after switching from "beta.0" to "beta.1", I get following swagger doc issues:

image

Is it an issue with this project or upstream issue?

**Comment by zMotivat0r** [comment]
@hakimio what issues? Could you please elaborate? (screenshot LGTM)

**Comment by zMotivat0r** [comment]
oh, you mean `s` query param? It's a new feature: now you can provide a json with search conditions. I will add docs soon

**Comment by zMotivat0r** [comment]
so basically you can do something like this

```typescript
{
  $or: [
    {
      foo: 'bar',
    },
    {
      name: 'some name',
      baz: {
        $or: {
          $notnull: true,
          $in: [1, 10]
        }
      }
    }
  ]
}
```

**Comment by hakimio** [comment]
@zMotivat0r no, I just mean that the cut-off readonly input field shouldn't be there. At least, I don't think it was there before. The one which says `s - Adds search condition. <a href="https://git`.

**Comment by zMotivat0r** [comment]
it just duplicates a `description`
https://github.com/swagger-api/swagger-ui/issues/3920

**Comment by hakimio** [comment]
Ok, so it's just an upstream issue and there is no way to get rid of it right now. Thanks for the link to the swagger issue.
