### ISSUE TITLE
update crud to the latest version

### ISSUE THREAD

**Issue by mohamedshedo** [nestjsx/crud#492]
I'm facing a lot of warnings and errors with my services when updating from 4.2.0 to 4.5.0 .in addition to that, a feature like require in the join of crud request not working properly

**Comment by zMotivat0r** [comment]
Could you elaborate?

**Comment by mohamedshedo** [comment]
everything works fine with V4.2.0 once I update the lib to 4.5.0 this a sample of the warnings

` node_modules/@nestjsx/crud-typeorm/lib/typeorm-crud.service.d.ts(23,5): error TS2416: Property 'decidePagination' in type 'TypeOrmCrudService<T>' is not assignable to the same property in base type 'CrudService<T>'.
[1]   Type '(parsed: import("/home/shedo/Desktop/Work/nestjs-backend/node_modules/@nestjsx/crud-request/lib/interfaces/parsed-request.interface").ParsedRequestParams, options: import("/home/shedo/Desktop/Work/nestjs-backend/node_modules/@nestjsx/crud/lib/interfaces/crud-options.interface").CrudRequestOptions) => boolean' is not assignable to type '(parsed: import("/home/shedo/Desktop/Work/nestjs-backend/node_modules/@nestjsx/crud/node_modules/@nestjsx/crud-request/lib/interfaces/parsed-request.interface").ParsedRequestParams, options: import("/home/shedo/Desktop/Work/nestjs-backend/node_modules/@nestjsx/crud/lib/interfaces/crud-options.interface").CrudRequest...'.
[1]     Types of parameters 'parsed' and 'parsed' are incompatible.
[1]       Type 'import("/home/shedo/Desktop/Work/nestjs-backend/node_modules/@nestjsx/crud/node_modules/@nestjsx/crud-request/lib/interfaces/parsed-request.interface").ParsedRequestParams' is not assignable to type 'import("/home/shedo/Desktop/Work/nestjs-backend/node_modules/@nestjsx/crud-request/lib/interfaces/parsed-request.interface").ParsedRequestParams'.
[1]         Types of property 'paramsFilter' are incompatible.
[1]           Type 'import("/home/shedo/Desktop/Work/nestjs-backend/node_modules/@nestjsx/crud/node_modules/@nestjsx/crud-request/lib/types/request-query.types").QueryFilter[]' is not assignable to type 'import("/home/shedo/Desktop/Work/nestjs-backend/node_modules/@nestjsx/crud-request/lib/types/request-query.types").QueryFilter[]'.
[1]             Type 'import("/home/shedo/Desktop/Work/nestjs-backend/node_modules/@nestjsx/crud/node_modules/@nestjsx/crud-request/lib/types/request-query.types").QueryFilter' is not assignable to type 'import("/home/shedo/Desktop/Work/nestjs-backend/node_modules/@nestjsx/crud-request/lib/types/request-query.types").QueryFilter'.
[1]               Types of property 'operator' are incompatible.
[1]                 Type 'ComparisonOperator' is not assignable to type 'DeprecatedCondOperator'.
[1]                   Type '"$eq"' is not assignable to type 'DeprecatedCondOperator'.
[1] node_modules/@nestjsx/crud/lib/decorators/feature-action.decorator.d.ts(2,74): error TS2694: Namespace '"/home/shedo/Desktop/Work/nestjs-backend/node_modules/@nestjs/common/index"' has no exported member 'CustomDecorator'.
[1] node_modules/@nestjsx/crud/lib/decorators/feature-action.decorator.d.ts(3,73): error TS2694: Namespace '"/home/shedo/Desktop/Work/nestjs-backend/node_modules/@nestjs/common/index"' has no exported member 'CustomDecorator'.
[1] src/claims/claims.controller.ts(41,14): error TS2420: Class 'ClaimsController' incorrectly implements interface 'CrudController<Claim>'.
[1]   Types of property 'service' are incompatible.
[1]     Type 'ClaimsService' is not assignable to type 'CrudService<Claim>'.
[1]       Types of property 'decidePagination' are incompatible.
[1]         Type '(parsed: import("/home/shedo/Desktop/Work/nestjs-backend/node_modules/@nestjsx/crud-request/lib/interfaces/parsed-request.interface").ParsedRequestParams, options: import("/home/shedo/Desktop/Work/nestjs-backend/node_modules/@nestjsx/crud/lib/interfaces/crud-options.interface").CrudRequestOptions) => boolean' is not assignable to type '(parsed: import("/home/shedo/Desktop/Work/nestjs-backend/node_modules/@nestjsx/crud/node_modules/@nestjsx/crud-request/lib/interfaces/parsed-request.interface").ParsedRequestParams, options: import("/home/shedo/Desktop/Work/nestjs-backend/node_modules/@nestjsx/crud/lib/interfaces/crud-options.interface").CrudRequest...'.
[1]           Types of parameters 'parsed' and 'parsed' are incompatible.
[1]             Type 'import("/home/shedo/Desktop/Work/nestjs-backend/node_modules/@nestjsx/crud/node_modules/@nestjsx/crud-request/lib/interfaces/parsed-request.interface").ParsedRequestParams' is not assignable to type 'import("/home/shedo/Desktop/Work/nestjs-backend/node_modules/@nestjsx/crud-request/lib/interfaces/parsed-request.interface").ParsedRequestParams'.
[1] src/claims/claims.controller.ts(47,9): error TS2322: Type 'this' is not assignable to type 'CrudController<Claim>'.
[1]   Type 'ClaimsController' is not assignable to type 'CrudController<Claim>'.
[1]     Types of property 'service' are incompatible.
[1]       Type 'ClaimsService' is not assignable to type 'CrudService<Claim>'.
[1] src/comments/comments.controller.ts(28,14): error TS2420: Class 'CommentsController' incorrectly implements interface 'CrudController<Comment>'.
[1]   Types of property 'service' are incompatible.
[1]     Type 'CommentsService' is not assignable to type 'CrudService<Comment>'.
[1]       Types of property 'decidePagination' are incompatible.
[1]         Type '(parsed: import("/home/shedo/Desktop/Work/nestjs-backend/node_modules/@nestjsx/crud-request/lib/interfaces/parsed-request.interface").ParsedRequestParams, options: import("/home/shedo/Desktop/Work/nestjs-backend/node_modules/@nestjsx/crud/lib/interfaces/crud-options.interface").CrudRequestOptions) => boolean' is not assignable to type '(parsed: import("/home/shedo/Desktop/Work/nestjs-backend/node_modules/@nestjsx/crud/node_modules/@nestjsx/crud-request/lib/interfaces/parsed-request.interface").ParsedRequestParams, options: import("/home/shedo/Desktop/Work/nestjs-backend/node_modules/@nestjsx/crud/lib/interfaces/crud-options.interface").CrudRequest...'.
[1]           Types of parameters 'parsed' and 'parsed' are incompatible.
[1]             Type 'import("/home/shedo/Desktop/Work/nestjs-backend/node_modules/@nestjsx/crud/node_modules/@nestjsx/crud-request/lib/interfaces/parsed-request.interface").ParsedRequestParams' is not assignable to type 'import("/home/shedo/Desktop/Work/nestjs-backend/node_modules/@nestjsx/crud-request/lib/interfaces/parsed-request.interface").ParsedRequestParams'.
[1] src/comments/comments.controller.ts(33,9): error TS2322: Type 'this' is not assignable to type 'CrudController<Comment>'.
[1]   Type 'CommentsController' is not assignable to type 'CrudController<Comment>'.
[1]     Types of property 'service' are incompatible.
[1]       Type 'CommentsService' is not assignable to type 'CrudService<Comment>'.
[1] src/insurance-companies/insurance-companies.controller.ts(20,14): error TS2420: Class 'InsuranceCompaniesController' incorrectly implements interface 'CrudController<InsuranceCompany>'.
[1]   Types of property 'service' are incompatible.
[1]     Type 'InsuranceCompaniesService' is not assignable to type 'CrudService<InsuranceCompany>'.
[1]       Types of property 'decidePagination' are incompatible.
[1]         Type '(parsed: import("/home/shedo/Desktop/Work/nestjs-backend/node_modules/@nestjsx/crud-request/lib/interfaces/parsed-request.interface").ParsedRequestParams, options: import("/home/shedo/Desktop/Work/nestjs-backend/node_modules/@nestjsx/crud/lib/interfaces/crud-options.interface").CrudRequestOptions) => boolean' is not assignable to type '(parsed: import("/home/shedo/Desktop/Work/nestjs-backend/node_modules/@nestjsx/crud/node_modules/@nestjsx/crud-request/lib/interfaces/parsed-request.interface").ParsedRequestParams, options: import("/home/shedo/Desktop/Work/nestjs-backend/node_modules/@nestjsx/crud/lib/interfaces/crud-options.interface").CrudRequest...'.
[1]           Types of parameters 'parsed' and 'parsed' are incompatible.
[1]             Type 'import("/home/shedo/Desktop/Work/nestjs-backend/node_modules/@nestjsx/crud/node_modules/@nestjsx/crud-request/lib/interfaces/parsed-request.interface").ParsedRequestParams' is not assignable to type 'import("/home/shedo/Desktop/Work/nestjs-backend/node_modules/@nestjsx/crud-request/lib/interfaces/parsed-request.interface").ParsedRequestParams'.
[1] src/medical-entity/medical-entity.controller.ts(35,14): error TS2420: Class 'MedicalEntityController' incorrectly implements interface 'CrudController<MedicalEntity>'.
[1]   Types of property 'service' are incompatible.
[1]     Type 'medicalEntityService' is not assignable to type 'CrudService<MedicalEntity>'.
[1]       Types of property 'decidePagination' are incompatible.
[1]         Type '(parsed: import("/home/shedo/Desktop/Work/nestjs-backend/node_modules/@nestjsx/crud-request/lib/interfaces/parsed-request.interface").ParsedRequestParams, options: import("/home/shedo/Desktop/Work/nestjs-backend/node_modules/@nestjsx/crud/lib/interfaces/crud-options.interface").CrudRequestOptions) => boolean' is not assignable to type '(parsed: import("/home/shedo/Desktop/Work/nestjs-backend/node_modules/@nestjsx/crud/node_modules/@nestjsx/crud-request/lib/interfaces/parsed-request.interface").ParsedRequestParams, options: import("/home/shedo/Desktop/Work/nestjs-backend/node_modules/@nestjsx/crud/lib/interfaces/crud-options.interface").CrudRequest...'.
[1]           Types of parameters 'parsed' and 'parsed' are incompatible.
[1]             Type 'import("/home/shedo/Desktop/Work/nestjs-backend/node_modules/@nestjsx/crud/node_modules/@nestjsx/crud-request/lib/interfaces/parsed-request.interface").ParsedRequestParams' is not assignable to type 'import("/home/shedo/Desktop/Work/nestjs-backend/node_modules/@nestjsx/crud-request/lib/interfaces/parsed-request.interface").ParsedRequestParams'.
[1] src/medical-entity/medical-entity.controller.ts(39,13): error TS2322: Type 'this' is not assignable to type 'CrudController<MedicalEntity>'.
[1]   Type 'MedicalEntityController' is not assignable to type 'CrudController<MedicalEntity>'.
[1]     Types of property 'service' are incompatible.
[1]       Type 'medicalEntityService' is not assignable to type 'CrudService<MedicalEntity>'.
[1] src/medical-group/medical-group.controller.ts(18,14): error TS2420: Class 'MedicalGroupController' incorrectly implements interface 'CrudController<MedicalGroup>'.
[1]   Types of property 'service' are incompatible.
[1]     Type 'MedicalGroupService' is not assignable to type 'CrudService<MedicalGroup>'.
[1]       Types of property 'decidePagination' are incompatible.`

**Comment by mohamedshedo** [comment]
@zMotivat0r the problem with require field in the join

`join: {
            'specialities': {
                eager: true,
                allow:[],
                 required:true
            }`

it's not working and still return an Inner join relation with the latest version

**Comment by zMotivat0r** [comment]
are you sure you haven't updated typescript or something? Because it seems like a typescript error not a crud lib.

>join: { 'specialities': { eager: true, allow:[], required:true }
it's not working and still return an Inner join relation with the latest version

But the whole point of `require: true` is to return an inner join, so what's the problem with it?

**Comment by mohamedshedo** [comment]
@zMotivat0r no the same version for typescript and node I have been working with.

it's not working regardless it's true or false with me .. always the same result

**Comment by zMotivat0r** [comment]
@mohamedshedo do you still have this issue? I haven't seen any other complaints about that except yours, so.
I would like to help, but I actually don't see how is that possible. I'm pretty much sure that something is wrong with your IDE or node_modules or even both - when an IDE stuck with types updating.

**Comment by mohamedshedo** [comment]
@zMotivat0r I tried to reinstall node_modules.
could give me the best tips and environment you work on with upgrade from versions

I work on node:13.3 and vscode the latest

**Comment by zMotivat0r** [comment]
I use nvm but work on node 12.16.3 LTS mostly, and latest vscode.

**Comment by mohamedshedo** [comment]
@zMotivat0r and the version of nestjs?

**Comment by mohamedshedo** [comment]
thank you for your support. it's fixed. the problem was with nestjs version 6 and typescript version
